# Generated by Django 4.2.10 on 2024-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Harsh', max_length=50),
            preserve_default=False,
        ),
    ]
